### ISSUE TITLE
sqlall and syncdb command fails

### ISSUE THREAD

**Issue by shoaib1987** [systers/vms#294]
**python manage.py syncdb**
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
**ImportError: No module named cities_light**
shoaib@shoaib-G50-80:~/work/openSourceProjects/python_related/vms/vms$ sudo pip install django-cities-light
The directory '/home/shoaib/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/shoaib/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting django-cities-light
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading django-cities-light-3.2.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from django-cities-light)
Requirement already satisfied (use --upgrade to upgrade): unidecode>=0.04.13 in /usr/local/lib/python2.7/dist-packages (from django-cities-light)
Requirement already satisfied (use --upgrade to upgrade): django-autoslug in /usr/local/lib/python2.7/dist-packages (from django-cities-light)
Requirement already satisfied (use --upgrade to upgrade): progressbar2>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from django-cities-light)
Requirement already satisfied (use --upgrade to upgrade): argparse in /usr/lib/python2.7 (from progressbar2>=3.6.0->django-cities-light)
Installing collected packages: django-cities-light
  Running setup.py install for django-cities-light ... done
**Successfully installed django-cities-light-3.2.0**
shoaib@shoaib-G50-80:~/work/openSourceProjects/python_related/vms/vms$ python manage.py syncdb
**Unknown command: 'syncdb'**
Type 'manage.py help' for usage.
shoaib@shoaib-G50-80:~/work/openSourceProjects/python_related/vms/vms$

**Comment by smarshy** [comment]
@shoaib1987 Seeing the commands, it looks as if you are trying to set it up locally. Which django version are you using? syncdb is deprecated after 1.7, if I am not wrong.

**Comment by shoaib1987** [comment]
Yes. As per the new installation guide Django (version >= 1.7 and version < 1.8) is required, my current version is :(1, 9, 5, 'final', 0).

**Comment by shoaib1987** [comment]
**$ python manage.py syncdb**
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 173, in build_graph
    self.load_disk()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 103, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/cities_light/migrations/0003_auto_20141120_0342.py", line 10, in <module>
    class Migration(migrations.Migration):
  File "/usr/local/lib/python2.7/dist-packages/cities_light/migrations/0003_auto_20141120_0342.py", line 21, in Migration
    preserve_default=True,
TypeError: __init__() got an unexpected keyword argument 'preserve_default'

My django version:
>>> import django
>>> django.VERSION
(1, 7, 0, 'final', 0)

**Comment by KokareIITP** [comment]
Are you sure you ran the command
sudo apt-get install python-psycopg2 
Try doing it if you haven't @shoaib1987 .

**Comment by smarshy** [comment]
@shoaib1987 Yes, try the above and if that still doesn't work, have a look at [this](http://stackoverflow.com/questions/26432242/django-1-7-migrations)
Try moving to version 1.7.1 from 1.7

**Comment by shoaib1987** [comment]
@KokareIITP  python-psycopg2 was already installed.  
sudo apt-get install python-psycopg2 
[sudo] password for shoaib: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**python-psycopg2 is already the newest version.**
The following packages were automatically installed and are no longer required:
  libgraphicsmagick3 libmng2 libxine1 libxine1-bin libxine1-ffmpeg
  libxine1-misc-plugins libxine1-plugins linux-image-3.16.0-33-generic
  linux-image-extra-3.16.0-33-generic
Use 'apt-get autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 110 not to upgrade.

@smarshy I was able to run "python manage.py syncdb" after moving to django version 1.7.1. Thank you.

**Comment by tapasweni-pathak** [comment]
@shoaib1987 Is the issue resolved now? Should I close the issue?

Thanks @KokareIITP, @smarshy for all the help.

**Comment by shoaib1987** [comment]
@tapasweni-pathak yes, please. Please note that I was able to run on Django 1.7.1, if same is the case with everyone else then we should document it. New installation guide has Django (version >= 1.7 and version < 1.8). 
Thanks @smarshy , @KokareIITP for prompt replies.

**Comment by tapasweni-pathak** [comment]
@shoaib1987 Feel free to submit a PR to fix the version in installation guide. Thanks for pointing it out.

**Comment by kamsuri** [comment]
Hi !
On running "python manage.py sqlall app_name_here", i am encountering the same error.
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/usr/lib/python2.7/dist-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named cities_light
`
Can anyone help me to resolve this?

**Comment by kamsuri** [comment]
Hi @tapasweni-pathak! 
I am an outreachy aspirant and want to contribute to this project, can you help me to resolve this error so that i can move ahead?

**Comment by tapasweni-pathak** [comment]
Which Django version have you setup for VMS in your local?

**Comment by kamsuri** [comment]
I have tried it with django version 1.7.1 and 1.7.4, but  none worked.

**Comment by tapasweni-pathak** [comment]
[Have a read](https://stackoverflow.com/questions/25762587/how-to-syncdb-in-django-1-7). You need do makemigrations and migrate instead of syncdb with these versions.

**Comment by kamsuri** [comment]
Thanks @tapasweni-pathak, it's resolved. 
Problem was due to variation in version and commands.
