### ISSUE TITLE
Command "python manage.py syncdb" requires a change in 'settings.py' before execution

### ISSUE THREAD

**Issue by malabikas** [systers/vms#302]
When running `python manage.py syncdb` as per the installation guide, the following error comes up in the prompt:
```
vagrant@vagrant-ubuntu-trusty-32:/vagrant/vms$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 57, in handle_noargs
    cursor = connection.cursor()
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 157, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 129, in _cursor
    self.ensure_connection()
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 124, in ensure_connection
    self.connect()
  File "/usr/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 112, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 116, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 179, in connect
    connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "myuser"
FATAL:  password authentication failed for user "myuser"

```
The settings.py file need to be manually changed to:
```
'USER' : 'vmsadmin',          
'PASSWORD' : '0xdeadbeef'
```

This isn't mentioned in the installation guide.

**Comment by tapasweni-pathak** [comment]
Can you submit a pull request for this change as well?

**Comment by KokareIITP** [comment]
@malabikas Please refer to project settings file [here](https://github.com/systers/vms/blob/develop/vms/vms/settings.py) these changes are already made in the setting file. Are you using an old version of vms?

**Comment by malabikas** [comment]
@KokareIITP Since I was referring [this](https://github.com/systers/vms/blob/develop/docs/Installation%20Guide.md#ppm) Installation Guide, they asked to clone `https://github.com/Nerdylicious/vms-integrated.git` . Should I submit a Pull Request to change it to `git clone https://github.com/systers/vms.git` and accordingly modify the steps?

**Comment by KokareIITP** [comment]
@malabikas .That would be great ! 🌻

**Comment by malabikas** [comment]
@KokareIITP Thanks for the prompt reply. On it! :+1:

**Comment by tapasweni-pathak** [comment]
@KokareIITP @malabikas To both of you. :+1:  :)

@malabikas May I close this now?

**Comment by malabikas** [comment]
Yes, please! And Issue [#303](https://github.com/systers/vms/issues/303) as well. :)
