### ISSUE TITLE
Autopep8 problem

### ISSUE THREAD

**Issue by vubo** [systers/vms#37]
Related to this comment https://github.com/systers/vms/pull/28#issuecomment-109070906 I tried to run the code through a pep8 locally. I have used [autopep8](https://pypi.python.org/pypi/autopep8/1.1.1) and got an error:

```
Traceback (most recent call last):
  File "V:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "V:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "V:\Python27\Scripts\autopep8.exe\__main__.py", line 5, in <module>
  File "V:\Python27\lib\site-packages\autopep8.py", line 119, in <module>
    DEFAULT_CONFIG = os.path.expanduser(r'~\.pep8')
  File "V:\Python27\lib\ntpath.py", line 310, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal
not in range(128)
```

**Comment by vubo** [comment]
https://github.com/myint/autoflake/issues/4
https://github.com/hhatto/autopep8/issues/139

**Comment by willingc** [comment]
@vubo I haven't used autopep8. My recommendation would be to use flake8 https://flake8.readthedocs.org/en/2.3.0/

FYI - flake8 is used by systers/portal project too.

**Comment by vubo** [comment]
@willingc thank you, I got it :+1:
