### ISSUE TITLE
Webdriver tests fail for no reason [build-fail]

### ISSUE THREAD

**Issue by tonythomas01** [systers/vms#512]
Look at these output: 

```
======================================================================
ERROR: setUpClass (registration.tests.test_functional_admin.SignUpAdmin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/systers/vms/vms/registration/tests/test_functional_admin.py", line 54, in setUpClass
    cls.driver = webdriver.Firefox()
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 103, in __init__
    self.binary, timeout)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 106, in _wait_until_connectable
    % (self.profile.path))
WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpAZnDcC If you specified a log_file in the FirefoxBinary constructor, check it for details.
``` 

all over in https://travis-ci.org/systers/vms/builds/294128344?utm_source=github_status&utm_medium=notification

**Comment by MeepyMay** [comment]
Please use the issue template.
